base_url = "https://monistowl.github.io/enoch/"
title = "Enoch"
description = "Enochian Chess Project"
default_language = "en"
compile_sass = true
taxonomies = []
author = "Tom Monistowl"

[extra]
favicon = "favicon.ico"
twitter = "monistowl"
github = "monistowl/enoch"
